<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import BaseDialog from '../components/BaseDialog.vue'
import EmptyState from '../components/EmptyState.vue'
import { analyzeSnapshot, executeCleanupBatch, getCandidates, getCleanupBatch, getTriageFiles, prepareCleanupBatch, selectFilteredTriage } from '../services/api'
import type { CleanupBatchResult, CleanupClassification, TriageFilters, TriageItem, TriageListing } from '../services/api'
import { useScanStore } from '../stores/scan'
import { formatBytes, formatLocalTime, formatNumber } from '../utils/format'

type UserTab = 'safe' | 'review' | 'protected'
type UserMode = 'safe' | 'review'
const store = useScanStore()
const scopeKey = ref<'system_drive_c' | 'current_user_temp'>(store.resultTarget === 'c_drive' ? 'system_drive_c' : 'current_user_temp')
const activeTab = ref<UserTab>('review')
const listing = ref<TriageListing | null>(null)
const loading = ref(false), error = ref(''), extensionText = ref(''), search = ref('')
const location = ref('all'), categories = ref<string[]>([]), minSize = ref(0), olderThanDays = ref(0)
const sort = ref<TriageFilters['sort']>('size_desc'), pageSize = ref<25 | 50 | 100>(50), offset = ref(0)
const selectedSafe = ref(new Set<string>()), selectedReview = ref(new Set<string>()), selectedTotalBytes = ref(0)
const confirmMode = ref<UserMode | null>(null), reviewAcknowledged = ref(false)
const processing = ref<{ batchId: string; completed: number; total: number } | null>(null)
const result = ref<CleanupBatchResult | null>(null)
let loadRequest = 0, progressTimer: ReturnType<typeof setInterval> | null = null

const tabClass: Record<UserTab, CleanupClassification> = { safe: 'SAFE_ACTIONABLE', review: 'REVIEW_REQUIRED', protected: 'DO_NOT_TOUCH' }
const tabLabel: Record<UserTab, string> = { safe: '可处理', review: '建议手动检查', protected: '不建议处理' }
const categoryOptions = [['video','视频'],['image','图片'],['audio','音频'],['document','文档'],['archive','压缩包'],['disk_image','磁盘镜像 / 虚拟机'],['backup','备份文件'],['data','数据文件'],['diagnostic','日志与诊断'],['temporary','临时类文件'],['installer','安装与程序'],['development','开发与项目'],['creative','设计与创作'],['other','其他文件']]
const reviewLocationOptions = [['downloads','下载'],['desktop','桌面'],['documents','文档'],['videos','视频'],['pictures','图片'],['music','音乐']]
const locationOptions = computed(() => scopeKey.value === 'current_user_temp'
  ? [['temporary', '当前用户临时文件']] : reviewLocationOptions)
const summary = computed(() => listing.value?.summary), currentItems = computed(() => listing.value?.items ?? [])
const selectedIds = computed(() => Array.from(confirmMode.value === 'safe' ? selectedSafe.value : selectedReview.value))
const activeUserFilter = computed(() => location.value !== 'all' || categories.value.length > 0 || extensionText.value.trim() !== '' || minSize.value > 0 || olderThanDays.value > 0 || search.value.trim() !== '')
const pageNumber = computed(() => Math.floor(offset.value / pageSize.value) + 1)
const totalPages = computed(() => Math.max(1, Math.ceil((listing.value?.matched_count ?? 0) / pageSize.value)))
const allSafeSelected = computed(() => currentItems.value.length > 0 && currentItems.value.every(item => selectedSafe.value.has(item.item_id)))

function extensions() { return extensionText.value.split(/[\s,;]+/).map(value => value.trim()).filter(Boolean) }
function filters(includePaging = true): TriageFilters { return { locations: location.value === 'all' ? [] : [location.value], categories: categories.value, extensions: extensions(), minSize: minSize.value || undefined, olderThanDays: olderThanDays.value || undefined, classifications: [tabClass[activeTab.value]], search: search.value.trim() || undefined, sort: sort.value, limit: pageSize.value, offset: includePaging ? offset.value : 0 } }
function resetSelection() { selectedSafe.value = new Set(); selectedReview.value = new Set(); selectedTotalBytes.value = 0 }
function toggleCategory(value: string) { categories.value = categories.value.includes(value) ? categories.value.filter(item => item !== value) : [...categories.value, value] }
function applyFilters() { offset.value = 0; resetSelection(); void load() }
function clearFilters() { location.value='all'; categories.value=[]; extensionText.value=''; minSize.value=0; olderThanDays.value=0; search.value=''; sort.value='size_desc'; applyFilters() }
function applySmart(value: Record<string, string[] | number>) { location.value=(value.locations as string[] | undefined)?.[0] ?? 'all'; categories.value=(value.categories as string[] | undefined) ?? []; minSize.value=Number(value.min_size ?? 0); olderThanDays.value=Number(value.older_than_days ?? 0); extensionText.value=''; search.value=''; applyFilters() }
function toggleSelection(mode: UserMode, item: TriageItem, checked: boolean) { const next=new Set(mode==='safe'?selectedSafe.value:selectedReview.value); if(checked) next.add(item.item_id); else next.delete(item.item_id); if(mode==='safe') selectedSafe.value=next; else selectedReview.value=next; selectedTotalBytes.value=currentItems.value.filter(row=>next.has(row.item_id)).reduce((sum,row)=>sum+row.size_bytes,0) }
function toggleAllSafe() { const selecting=!allSafeSelected.value; selectedSafe.value=selecting?new Set(currentItems.value.map(item=>item.item_id)):new Set(); selectedTotalBytes.value=selecting?currentItems.value.reduce((sum,item)=>sum+item.size_bytes,0):0 }
async function selectCurrentFiltered() { if(!activeUserFilter.value){error.value='请先使用位置、类型、扩展名、大小、时间或搜索条件缩小范围。';return} error.value=''; try{const chosen=await selectFilteredTriage(scopeKey.value,filters(false));if(activeTab.value==='safe')selectedSafe.value=new Set(chosen.item_ids);else selectedReview.value=new Set(chosen.item_ids);selectedTotalBytes.value=chosen.matched_bytes}catch(cause){const message=cause instanceof Error?cause.message:'';error.value=message.includes('TRIAGE_SELECTION_TOO_LARGE')?'当前筛选有超过 200 个文件。一次最多选择 200 个，请继续缩小筛选条件。':'无法选择当前筛选结果，请缩小范围后重试。'} }
function openConfirmation(mode: UserMode){const ids=mode==='safe'?selectedSafe.value:selectedReview.value;if(!ids.size)return;confirmMode.value=mode;reviewAcknowledged.value=false;result.value=null}
function closeConfirmation(){if(processing.value)return;confirmMode.value=null;reviewAcknowledged.value=false}
async function load(){if(!store.sessionReady)return;const request=++loadRequest;loading.value=true;error.value='';try{if(scopeKey.value==='current_user_temp'){const candidates=await getCandidates({scopeKey:scopeKey.value,limit:1});if(candidates.latest_snapshot&&candidates.run?.snapshot_id!==candidates.latest_snapshot.snapshot_id)await analyzeSnapshot(candidates.latest_snapshot.snapshot_id)}const next=await getTriageFiles(scopeKey.value,filters());if(request===loadRequest)listing.value=next}catch{if(request===loadRequest){listing.value=null;error.value='暂时无法读取整理索引，请稍后重试或先完成一次扫描。'}}finally{if(request===loadRequest)loading.value=false}}
function reasonMessage(code:string|null){return({TARGET_CHANGED_SINCE_SCAN:'文件已经发生变化',TARGET_CHANGED_SINCE_PREPARE:'文件在确认后发生了变化',TARGET_NO_LONGER_EXISTS:'文件已经不存在',ACCESS_DENIED:'当前没有权限',TARGET_IN_USE:'文件正在使用中',EXECUTION_REPARSE_POINT_BLOCKED:'文件位置变成了系统链接',EXECUTION_CROSS_VOLUME_BLOCKED:'文件位置跨越了其他磁盘',BATCH_CLASSIFICATION_CHANGED:'当前安全分类已经变化',BATCH_ITEM_NO_LONGER_AVAILABLE:'扫描记录中的项目已经不可用',RECYCLE_ORIGINAL_PATH_REMAINS:'无法确认文件已进入回收站'} as Record<string,string>)[code??'']??'当前安全规则不允许处理'}
async function updateProgress(batchId:string){try{const audit=await getCleanupBatch(batchId);const completed=audit.items.filter(item=>item.execute_result!==null).length;if(processing.value?.batchId===batchId)processing.value={...processing.value,completed}}catch{/* result is authoritative */}}
async function confirmBatch(){const mode=confirmMode.value;if(!mode||!selectedIds.value.length||(mode==='review'&&!reviewAcknowledged.value))return;error.value='';try{const prepared=await prepareCleanupBatch(selectedIds.value,mode,scopeKey.value);if(!prepared.execution_token||!prepared.approved_count){error.value='所选文件没有通过处理前的实时安全检查。';confirmMode.value=null;return}processing.value={batchId:prepared.batch_id,completed:0,total:prepared.approved_count};progressTimer=setInterval(()=>void updateProgress(prepared.batch_id),250);result.value=await executeCleanupBatch(prepared.execution_token);resetSelection();confirmMode.value=null;await load()}catch{error.value='处理没有完成；DiskScope 未使用永久删除。请查看未处理原因后重试。'}finally{if(progressTimer)clearInterval(progressTimer);progressTimer=null;processing.value=null}}
async function copyPath(path:string){try{await navigator.clipboard.writeText(path)}catch{error.value='无法复制路径，请检查浏览器剪贴板权限。'}}
watch(()=>store.sessionReady,ready=>{if(ready)void load()},{immediate:true})
watch(scopeKey,()=>{activeTab.value=scopeKey.value==='system_drive_c'?'review':'safe';clearFilters()})
watch(activeTab,()=>{offset.value=0;resetSelection();void load()})
onBeforeUnmount(()=>{if(progressTimer)clearInterval(progressTimer)})
</script>

<template>
  <div class="page-heading"><div><p class="eyebrow">扫描后的下一步</p><h1>清理空间</h1><p class="page-description">快速找出值得检查的内容，再由你决定是否移入 Windows 回收站。</p></div><span class="read-only-chip">不会永久删除</span></div>
  <section class="panel cleanup-source"><div><strong>可供整理的个人文件索引</strong><p>只整理个人目录中的文件元数据；真正处理前仍会重新检查每个文件。</p></div><label>扫描位置<select v-model="scopeKey" :disabled="loading||!!processing"><option value="system_drive_c">Windows C 盘</option><option value="current_user_temp">临时文件</option></select></label></section>
  <p v-if="error" class="inline-error" role="alert">{{ error }}</p><p v-if="loading" class="inline-note" aria-live="polite">正在整理可筛选的文件…</p>
  <template v-if="listing?.index_available&&summary">
    <section class="cleanup-summary" aria-label="清理建议分类摘要"><button type="button" :class="{active:activeTab==='safe'}" @click="activeTab='safe'"><span>可处理</span><strong>{{ formatBytes(summary.SAFE_ACTIONABLE.bytes) }}</strong><small>{{ formatNumber(summary.SAFE_ACTIONABLE.count) }} 个文件</small></button><button type="button" :class="{active:activeTab==='review'}" @click="activeTab='review'"><span>建议手动检查</span><strong>{{ formatBytes(summary.REVIEW_REQUIRED.bytes) }}</strong><small>{{ formatNumber(summary.REVIEW_REQUIRED.count) }} 个文件</small></button><button type="button" :class="{active:activeTab==='protected'}" @click="activeTab='protected'"><span>不建议处理</span><strong>{{ formatBytes(summary.DO_NOT_TOUCH.bytes) }}</strong><small>{{ formatNumber(summary.DO_NOT_TOUCH.count) }} 个文件</small></button></section>
    <p v-if="listing.coverage" class="coverage-note">已扫描个人文件 {{ formatNumber(listing.coverage.observed_count) }} 个，已建立整理索引 {{ formatNumber(listing.coverage.persisted_count) }} 个；覆盖状态：{{ listing.coverage.status==='complete'?'完整':'部分' }}。筛选结果不代表整个 C 盘的全部文件。</p>
    <section v-if="listing.smart_views.some(view=>view.count)" class="panel smart-section"><div class="panel-heading"><div><p class="eyebrow">快速找出值得检查的内容</p><h2>智能视图</h2></div></div><div class="smart-grid"><button v-for="view in listing.smart_views.filter(item=>item.count)" :key="view.key" type="button" @click="applySmart(view.filters)"><strong>{{ view.label }}</strong><span>{{ formatNumber(view.count) }} 个 · {{ formatBytes(view.bytes) }}</span></button></div></section>
    <section class="panel triage-filters" aria-label="文件筛选与排序"><div class="panel-heading"><div><p class="eyebrow">缩小范围</p><h2>筛选与排序</h2></div><button type="button" class="text-button" @click="clearFilters">清除筛选</button></div><div class="filter-row"><label>位置<select v-model="location"><option value="all">{{ scopeKey==='current_user_temp'?'全部临时文件':'全部个人目录' }}</option><option v-for="option in locationOptions" :key="option[0]" :value="option[0]">{{ option[1] }}</option></select></label><label>最小大小<select v-model.number="minSize"><option :value="0">不限</option><option :value="100*1024**2">100 MB</option><option :value="500*1024**2">500 MB</option><option :value="1024**3">1 GB</option><option :value="5*1024**3">5 GB</option><option :value="10*1024**3">10 GB</option></select></label><label>未修改时间<select v-model.number="olderThanDays"><option :value="0">不限</option><option :value="30">30 天以上</option><option :value="90">90 天以上</option><option :value="180">180 天以上</option><option :value="365">365 天以上</option></select></label><label>排序<select v-model="sort"><option value="size_desc">大小从大到小</option><option value="mtime_asc">最久未修改优先</option><option value="name_asc">名称</option><option value="path_asc">路径</option></select></label></div><div class="category-filters" aria-label="文件类别（可多选）"><button v-for="option in categoryOptions" :key="option[0]" type="button" :class="{active:categories.includes(option[0])}" :aria-pressed="categories.includes(option[0])" @click="toggleCategory(option[0])">{{ option[1] }}</button></div><div class="filter-row filter-search"><label>扩展名<input v-model="extensionText" placeholder=".zip, .mkv, .iso" @keyup.enter="applyFilters"></label><label>文件名或路径<input v-model="search" placeholder="输入关键词" @keyup.enter="applyFilters"></label><button type="button" class="primary-button" @click="applyFilters">应用筛选</button></div></section>
    <section class="panel cleanup-panel"><div class="panel-heading cleanup-heading"><div><p class="eyebrow">{{ tabLabel[activeTab] }}</p><h2>找到 {{ formatNumber(listing.matched_count) }} 个文件，共 {{ formatBytes(listing.matched_bytes) }}</h2></div><div class="list-actions"><button v-if="activeTab==='safe'&&currentItems.length" type="button" class="text-button" @click="toggleAllSafe">{{ allSafeSelected?'取消全选':'全选当前列表' }}</button><button v-if="activeTab!=='protected'" type="button" class="text-button" :disabled="activeTab==='review'&&!activeUserFilter" @click="selectCurrentFiltered">选择当前筛选结果</button></div></div>
      <p v-if="activeTab==='review'" class="coverage-note">DiskScope 无法判断这些个人文件是否仍然有用，因此不会默认选择，也不提供无条件一键全选。请先筛选，再选择当前筛选结果。</p><p v-if="activeTab==='protected'" class="coverage-note">程序与危险类型只供查看和搜索，不提供勾选或强制处理入口。</p>
      <div v-if="currentItems.length" class="cleanup-list"><article v-for="item in currentItems" :key="item.item_id" class="cleanup-item"><label v-if="activeTab !== 'protected'" class="cleanup-check"><input type="checkbox" :checked="activeTab==='safe'?selectedSafe.has(item.item_id):selectedReview.has(item.item_id)" :aria-label="`选择 ${item.name}`" @change="toggleSelection(activeTab==='safe'?'safe':'review',item,($event.target as HTMLInputElement).checked)"></label><div class="cleanup-item-main"><div class="cleanup-item-title"><strong>{{ item.name }}</strong><span>{{ formatBytes(item.size_bytes) }}</span></div><p class="cleanup-path" :title="item.display_path">{{ item.display_path }}</p><div class="item-tags"><span>{{ item.category_label }}</span><span>{{ item.location_group }}</span><span>{{ item.extension||'无扩展名' }}</span></div><p v-if="item.category==='disk_image'||item.category==='creative'" class="item-warning">此类文件可能包含项目、虚拟机或创作素材，请确认用途后再处理。</p><div class="cleanup-item-actions"><span>{{ item.age_days===null?'修改时间不可用':`${formatNumber(item.age_days)} 天未修改` }} · {{ formatLocalTime(item.mtime) }}</span><button type="button" class="table-action" @click="copyPath(item.display_path)">复制路径</button></div></div></article></div>
      <div v-else-if="activeTab==='safe'&&summary.REVIEW_REQUIRED.count" class="zero-safe-state"><EmptyState title="暂时没有可以直接处理的文件" description="你可以查看需要自己判断的个人文件。"/><button type="button" class="primary-button" @click="activeTab='review'">查看建议检查的文件</button></div><EmptyState v-else title="当前筛选没有结果" description="可以调整筛选条件，或选择其他分类。"/>
      <div v-if="listing.matched_count" class="pagination"><button type="button" :disabled="offset===0" @click="offset=Math.max(0,offset-pageSize);load()">上一页</button><span>第 {{ pageNumber }} / {{ totalPages }} 页</span><button type="button" :disabled="offset+pageSize>=listing.matched_count" @click="offset+=pageSize;load()">下一页</button><label>每页<select v-model.number="pageSize" @change="offset=0;load()"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></label></div>
      <div v-if="activeTab==='safe'&&selectedSafe.size" class="selection-toolbar"><span>已选择 {{ selectedSafe.size }} 个文件 · {{ formatBytes(selectedTotalBytes) }}</span><button type="button" class="primary-button" @click="openConfirmation('safe')">移入 Windows 回收站</button></div><div v-if="activeTab==='review'&&selectedReview.size" class="selection-toolbar"><span>已选择 {{ selectedReview.size }} 个文件 · {{ formatBytes(selectedTotalBytes) }}</span><button type="button" class="primary-button" @click="openConfirmation('review')">继续确认</button></div>
    </section>
    <section v-if="!summary.SAFE_ACTIONABLE.count&&!summary.REVIEW_REQUIRED.count" class="panel no-action-state"><h2>当前没有适合通过 DiskScope 处理的文件</h2><p>你仍可以继续了解空间占用，或在文件发生变化后重新扫描。</p><div><RouterLink to="/analysis">查看空间分析</RouterLink><RouterLink to="/large-items">查看大文件</RouterLink></div></section>
  </template>
  <EmptyState v-else-if="listing&&!listing.index_available" title="这条扫描记录还没有整理索引" :description="listing.message||'重新扫描后可使用完整筛选功能。'"/><EmptyState v-else-if="!loading" title="还没有可用的扫描记录" description="请先扫描 C 盘或临时文件，再回到这里查看能做什么。"/>
  <section v-if="processing" class="panel processing-panel" aria-live="polite"><strong>正在移入 Windows 回收站</strong><p>正在处理 {{ processing.completed }} / {{ processing.total }}；请保持 DiskScope 打开。</p></section>
  <section v-if="result" class="panel batch-result" aria-live="polite"><div class="panel-heading"><div><p class="eyebrow">处理结果</p><h2>处理完成</h2></div><span class="status-pill completed">{{ result.success_count }} 个成功</span></div><div class="result-counts"><span>成功：{{ result.success_count }}</span><span>跳过：{{ result.skipped_count }}</span><span>失败：{{ result.failed_count }}</span></div><p>已将 {{ formatBytes(result.recycled_bytes) }} 的文件移入 Windows 回收站。</p><p class="coverage-note">这些文件仍可能占用磁盘空间；DiskScope 不会自动清空回收站。</p><details v-if="result.items.some(item=>item.result!=='recycled')" class="technical-details"><summary>查看未处理原因</summary><ul><li v-for="item in result.items.filter(entry=>entry.result!=='recycled')" :key="item.item_id">{{ reasonMessage(item.reason) }} <span class="mono">({{ item.reason }})</span></li></ul></details></section>
  <BaseDialog :open="confirmMode!==null" title-id="batch-confirm-title" description-id="batch-confirm-description" :close-on-backdrop="!processing" @close="closeConfirmation"><h2 id="batch-confirm-title">{{ confirmMode==='safe'?'移入 Windows 回收站？':'确认处理这些文件？' }}</h2><div id="batch-confirm-description"><p>已选择 {{ selectedIds.length }} 个文件，总大小约 {{ formatBytes(selectedTotalBytes) }}。</p><p v-if="confirmMode==='safe'">这些文件已经通过 DiskScope 当前的安全检查。处理后会进入 Windows 回收站，不会永久删除。</p><template v-else><p>“很久未修改”不等于“肯定没用”。DiskScope 无法替你确认文件内容是否重要。</p><label class="acknowledgement"><input v-model="reviewAcknowledged" type="checkbox"> 我已经检查过所选文件，并确认不再需要</label></template></div><div class="confirm-actions"><button type="button" class="text-button" :disabled="!!processing" @click="closeConfirmation">取消</button><button type="button" class="primary-button" data-dialog-initial :disabled="!!processing||(confirmMode==='review'&&!reviewAcknowledged)" @click="confirmBatch">移入回收站</button></div></BaseDialog>
</template>
